### ISSUE TITLE
Add hot reload option

### ISSUE THREAD

**Issue by henricook** [softwaremill/realworld-tapir-zio#144]
It'd be great to have the ability to hot reload when code changes while the app's running (e.g. with `sbt run`). I think it's fair to say it's something most developers would want as they build, and a common thing to add to a Scala app.

**Comment by wydra98** [comment]
I will gladly add it to the project, but do you know any library that I could use for this?

**Comment by adamw** [comment]
I think the standard way is to use https://github.com/spray/sbt-revolver, but maybe there's something else as well
