### ISSUE TITLE
How can I inject a `Client`?

### ISSUE THREAD

**Issue by henricook** [softwaremill/realworld-tapir-zio#145]
I'm sorry to raise a support issue here, I found it really hard to find an example of dependency injection working this way in ZIO projects online, but I could just be searching it poorly. I'm hoping you might be able to provide some advice (if not we can close this).

One of the first things I tried when playing with this project was to inject my own HTTP Client (`zio.http.Client` seemed the natural choice) but try as I might I can't find the right combination of options to inject it into a service.

Here's an example of what I tried:

1. Add `Client.live` to the layers in `Main.scala`
2. Try and inject it into e.g. the `ArticlesService` with:
```
class ArticlesService(
                     client: Client.type,
    articlesRepository: ArticlesRepository,
    usersRepository: UsersRepository
):
```
...
```
  val live: ZLayer[Client.type with ArticlesRepository with UsersRepository, Nothing, ArticlesService] =
    ZLayer.fromFunction(ArticlesService(_, _, _))
```

3. Use `client.request("https://www.test.com")` in a method

This results in an error that I don't really understand, like:

```
[error]    | Your effect requires a service that is not in the environment.
[error]    | Please provide a layer for the following type:
[error]    |
[error]    |   1. zio.http.ZClient[scala.Any, zio.http.Body, scala.Throwable, zio.http.Response]
[error]    |
[error]    | Call your effect's provide method with the layers you need.
[error]    | You can read more about layers and providing services here:
[error]    | 
[error]    |   https://zio.dev/reference/contextual/
[error]    |
[error]    |──────────────────────────────────────────────────────────────────────
[error]    |
[error] 20 |    res <- Client.request("https://www.test.com")
[error] 21 |    data <- res.body.asString
[error] 22 |    _ <- ZIO.fail(Unauthorized("Error"))
```

If you have a minute I feel like I'm missing something fundamental here that'll probably be easy to correct me on?

Thanks in advance

**Comment by wydra98** [comment]
Hi, could you show how your Client class looks like? The error suggests that you haven't provided a Zlayer for that class, which enables the injection mechanism. Maybe you need to wrap what Client.live returns in a ZLayer, but I would need to see the code ;)

**Comment by henricook** [comment]
I got _something_ working here in the end but I don't know if it's good or not.

In the `Main.scala` I added `Client.default` to the zlayers


Then in my service's wiring:

```
  val live: ZLayer[Client & UsersRepository, Nothing, StormMigratorService] =
    ZLayer.fromFunction(StormMigratorService(_, _))
    ```
    
 And it's constructor:  

 ```
    class StormMigratorService(
  client: Client,
  usersRepository: UsersRepository,
):
```

While that _seems_ easy the annoying thing here is that `client: Client` doesn't have the same interface as the static `Client` you can call from anywhere. For example you can do `Client.request(url: String)` but with the injected `client` the best you can do it `client.request(req: Request)` - and it's ugly making a request every time when a string `url` would have been enough.

I think this is likely a problem with the zio-http project and how they've made all this work though, unless you can see a way to inject the same thing that `Client` is?

I also had some luck just using `Client` but then I had to add a `.provide(Client.live)` to the method in the ServerEndpoints class, which felt pretty grimy/not the intended way of doing things

**Comment by wydra98** [comment]
Yes, the problem definitely is with the difference in the interface for: `client: Client` and the static `Client`. 
I've just tried to implement `Client.request(url: String)` in any service, and I wasn't able to do it because I couldn't match the new types that appeared there.

For example, in the `ArticleService`, instead of returning `Task[Article]` in some functions, we return `RIO[Client, Article]` because our effect requires the `Client`. However, changing the type is quite significant and it's difficult to adjust the rest of the project accordingly.

So if you managed to make it work in a way that it functions correctly, it would probably be the best solution. Alternatively, could you send me the branch where you're working on it so that I can take a look? ;)

**Comment by henricook** [comment]
Thanks, it's great to have you confirm that for me! So the way I described above appears to work, but with weird interface caveats from zio-http, maybe I'll bring that up with them in a new issue.

Cheers!

**Comment by adamw** [comment]
Sorry to chime in late to the game, but one thing that look suspicious is this:

```
class ArticlesService(
                     client: Client.type,
    articlesRepository: ArticlesRepository,
    usersRepository: UsersRepository
):
```

Instead, you should depend on an instance of the `Client` [type](https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/package.scala#L48-L49), that is:

```
class ArticlesService(
                     client: Client,
    articlesRepository: ArticlesRepository,
    usersRepository: UsersRepository
):
```

Indeed, `ZClient.live` the provides an instance of that type (https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/ZClient.scala#L800)
