### ISSUE TITLE
Endpoint and ServerEndpoint mixed. It is very hard to share Endpoint between scalajs as frontend and scalajvm as backend.

### ISSUE THREAD

**Issue by benluo** [softwaremill/realworld-tapir-zio#169]
If I want to make a full-stack web app. Tapir is perfect for share endpoint between backend and frontend. But if use your template as baseline, it is very hard to do full-stack web app.  My idea is 

- shared (for backend and frontend . use pure Tapir Endpoint)
- backend (use ServerEndpoint based on shared Endpoint)
- frontend (use Endpoint to fetch data from backend).

**Comment by benluo** [comment]
found way.

**Comment by adamw** [comment]
@benluo maybe you could describe briefly your approach, if anybody encounters a similar problem / has a similar idea?

**Comment by benluo** [comment]
let me prepare a small demo in next few weeks.

**Comment by benluo** [comment]
https://github.com/dallinhuff/zio-tpilot 
it's the perfect example to share tapir between backend and frontedn.

**Comment by adamw** [comment]
@benluo thanks!

**Comment by adamw** [comment]
I added the project to the list of third-party tapir examples: https://github.com/softwaremill/tapir/commit/dee2dad1c8cf55752a1ba77c2ff2d6ce228cba54
