### ISSUE TITLE
Using recursive comparison assertions - refactor probably needed

### ISSUE THREAD

**Issue by FawnPug** [softwaremill/realworld-tapir-zio#35]
For example in AssertJ this is easy and clear:
https://stackoverflow.com/questions/43316133/how-to-compare-recursively-ignoring-given-fields-using-assertj

However in this project we used diffx library and such assertions with ignoring fields look following:

yield assertTrue {
          // TODO there must be better way to implement this...
          import com.softwaremill.realworld.common.model.ArticleDiff.{*, given}
          compare(
            result.toOption.get,
            Article(
              ArticleData(
                "how-to-train-your-dragon-2",
                "How to train your dragon 2",
                "So toothless",
                "Its a dragon",
                List("drogon", "fly"),
                null,
                null,
                false,
                0,
                ArticleAuthor("admin", Some("I dont work"), Some(""), following = false)
              )
            )
          ).isIdentical
        }

This is not the best approach, we should find more elegant way to achieve this goal / refactor it.

**Comment by bartma11** [comment]
I looked into it. Maybe we can just use plain old `==`? On case classes it performs a recursive comparison on all fields. As for fields that do not require checking, maybe we can define a separate smaller case class, let's call it ReducedResponse. We can transform Response into this ReducedResponse and then just use `==` to compare with given example. I will prepare a PR to illustrate.

**Comment by bartma11** [comment]
We can add `import zio.test.magnolia.diff._`. If we do that we should get a nice diff when there will be a difference between values.
