### ISSUE TITLE
Swagger authorization is not working

### ISSUE THREAD

**Issue by wydra98** [softwaremill/realworld-tapir-zio#53]
In swagger, you can't insert the token returned after logging into the header

**Comment by wydra98** [comment]
After discussion we wrote that we will leave the Swagger with not working token section. It's not working correctly, but it can help as documentation.

**Comment by adamw** [comment]
Hm this should work I think, maybe you can elaborate on the problem? Are the inputs designated as authentication inputs? https://tapir.softwaremill.com/en/latest/endpoint/security.html#authentication-inputs
